### ISSUE TITLE
Missing module '.config/db'

### ISSUE THREAD

**Issue by ashish-puttaa** [ashwinkumar1211/Socialnetwork#2]
### 🐛 Bug Report

When I was trying to set up, I ran into an error due to a missing module `.config/db` in server.js

![server](https://user-images.githubusercontent.com/37892563/82837567-14b10180-9ee7-11ea-8635-67817beeea99.JPG)

### 🤔 Expected Behavior

Imports all files without error.

### 😯 Current Behavior

![ashwin issue (2)_censored (1)](https://user-images.githubusercontent.com/37892563/82837384-7e7cdb80-9ee6-11ea-9694-5dc6f53e3f62.jpg)

### 💁 Possible Solution
I looked through the entire repository if the module was misplaced.
It turns out that the **config folder is missing** in your repo. @ashwinkumar1211

**Comment by ashwinkumar1211** [comment]
Purposefully removed the config module from project structure and that's causing the missing module error. Check the commit status if you want.(2)  And more importantly the config module had "authentication key" which can not be publically portrayed. I'll be glad to upload the config structure though. Closing this thread with a hope you got it.

**Comment by ashish-puttaa** [comment]
Yeah I checked the previous commit. It looks like the **db.js file** contains some important code that **sets up the mongodb connection**. Your project needs to establish a connection with the database to work. I'd suggest that you keep those files and just replace the authentication keys with some template strings. 

Also **change your secret keys**. You may have removed them in the latest commit, but anyone can go through your previous commit and steal them.

@ashwinkumar1211

**Comment by ashwinkumar1211** [comment]
@ashish-puttaa Thanks for pointing it. I found that .gitignore was messing around from the beginning. So removed the branch which obviously deleted the history (anyway changed the secret :P) and added a proper config folder with db.js ( you can check it out now ).
